[package]
name = "fasttls"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies]
libc = "0.2.2"
rustls = "0.22.0"
rustls-pemfile = "2.0.0"
rustls-pki-types = "1.0.1"
rustls-webpki = "0.102.0"
rcgen = "0.12.0"
webpki-roots = "0.26.0"
memoffset = "0.9.0"
